* Packaging

  Appman shall be distributed as a Debian package for Ubuntu 17.10. The .deb
  package shall automatically set up the package and all dependencies.

** Installing

   To build the package, run:

   #+BEGIN_SRC bash
   $ sbt Debian/packageBin
   #+END_SRC

   It can then be installed by running:

   #+BEGIN_SRC bash
   $ sudo dpkg -i target/appman_*_all.deb
   #+END_SRC

   This package does not depend on the build system, and can be freely moved to
   a separate target computer.

** Access

   The system should now be accessible at [[http://localhost:9000/]]!

** Hardening

*** Passwords

    After installation the application secret and PostgreSQL password MUST
    be changed. To do this, first generate both passwords (perhaps using
    ~pwgen~):

    #+BEGIN_SRC bash
    $ pwgen 20 2
    #+END_SRC

    Then change the PostgreSQL password:

    #+BEGIN_SRC bash
    $ sudo -u appman psql -c '\password'
    #+END_SRC

    Then you need to tell appman about the new passwords by modifying
    ~PGPASSWORD~ and ~APPLICATION_SECRET~ in ~/etc/default/appman~.

    Finally, restart Appman to apply the new settings:

    #+BEGIN_SRC bash
    $ sudo systemctl restart appman.service
    #+END_SRC

*** TLS/HTTPS

    Appman SHOULD only be accessible using HTTPS. Setting this up is out of
    scope for this document, but can be done using a reverse proxy, such as
    NGINX or Apache HTTPD.

** Creating an Administrator account

   There is no administrator account created when Appman is installed. To
   promote a user, first create an account at [[http://localhost:9000/register]].
   Then run the following to set its role:

   #+BEGIN_SRC bash
   sudo -u appman psql -c "UPDATE users SET role='Admin' WHERE username='<YOUR_USERNAME>'"
   #+END_SRC
